- Week01/두_배열의_원소_교체/김지연.py
- Week01/미로_탈출/김지연.py
- Week01/부품_찾기/김지연.py
- Week01/상하좌우/김지연.py
- Week01/음료수_얼려_먹기/김지연.py
- Problem: 두 배열의 원소 교체(이코테)
- Issue: [#1]()
- 시도 횟수: 2번
- 풀이 시간: 20m 32s
최대 k번 교체할 수 있단말은 k까지 교체안하고 a배열을 최대로 만들 수 있다는 경우가 있다는것 즉, a와 b를 계속 비교하면서
a = [6, 4, 3, 3]
b = [5, 3, 2, 2] 일경우  첫번재 교환 a = [6, 5, 3, 3], b = [4, 3, 2, 2]일 텐데 이때 b[0]과 adml [2]를 교환하는게 최댓값을 구할 수 있는거 아닌가?
첫번째 풀이: a배열과 b배열 원소하나를 비교할 때마다 sort()함수를 사용해서 시간복잡도가 많이 나옴.. 이렇게 복잡하게 푸러야하나해서 다시 풀어봄
a배열이 오름 차순으로 정렬된다는 점을 간과했다... a[i]와 b[i]를 비교해서 a[i] > b[i]일 경우 더 이상 비교할 필요가 없음. 왜냐하면 a[i]이후 원소는 a[i]보다 큰 원소일 것이고, b[i]이후 원소는 b[i]보다 작은 원소이므로 현재 a배열에 있는 원소가 최댓값이 된다.
a배열은 `sort()`함수를 사용하여 오름 차순으로 정렬하고,
b배열은 `sort(reverse=True)`를 사용하여 내림 차순으로 정렬
- `O(NlogN)`
-----
- Problem: 미로 탈출(이코테)
- Issue: [#1]()
- 시도 횟수: 2번
- 풀이 시간: 28m 40s
소스코드가 한번 날아가서 두번시도 한 셈... 
처음 풀이했을 때는 bfs로 탐색해야겠다는 것까지는 쉽게 떠올렸다. 
근데 최소 노드 개수를 어떻게 세야할지가 관건이였음
정답을 슬쩍보면서 풀긴 …
> [Week01] jiyeon

- Week03/codeup6097.py
- Week03/문자열_뒤집기.py
- Week03/문자열_뒤집기/문자열.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> [Week03] yongson

- Week03/도시_분할_계획/도시_분할_계획_조수지.py
- Week03/문자열_뒤집기/문자열_뒤집기_조수지.py
- Week03/커리큘럼/커리큘럼_조수지.py
- Week03/팀_결성/팀_결성_조수지.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> [Week03] suji

- Week03/도시_분할_계획/김지연.py
- Week03/문자열_뒤집기/김지연.py
- Week03/성격유형 검사하기/김지연.py
- Week03/커리큘럼/김지연.py
- Week03/팀_결성/김지연.py
- Problem: [도시 분할 계획](https://www.acmicpc.net/problem/1647)
- Issue: [#17  ]()
- 시도 횟수: 1
- 풀이 시간: 37m
최소 신장 트리를 활용하여 마을의 길을 최소화하고 마지막에 연결한 간선 비용이 제일 크므로 마지막에 연결한 간선을 제거하여 마을 2개를 만든다.
모든 도시를 최소신장트리로 구한 다음에 맨 마지막에 연결한 간선을 제외하면 됨.
- `O(ElogE)`
------------------------
- Problem: [문자열 뒤집기](https://www.acmicpc.net/problem/1439)
- Issue: [#17  ]()
- 시도 횟수: 1
- 풀이 시간: 6m 52s
0과 1이 연속된 걸 하나로 보고(00011101100 -> 01010) 0을 기준으로 나누고, 1을 기준으로 나누고 해서 0과 1의 개수를 비교하여 작은 수를 출력
split() 내장 함수를 사용하여 '0', '1' 기준으로 나눠준 리스트를 비교하여 min값을 출력
- `O(n)`
------------------
- Problem: [커리큘럼] (이코테)
- Issue: [#17  ]()
- 시도 횟수: 2
- 풀이 시간: 57m
문제 이름부터 위상정렬 사용해달라고 나와있음. 위상정렬 활용해서 각 과목을 듣기 위한 최소 시간을 구하는 건데, 여기서 조금 막히기 시작함. 각 과목에서 max를 사용해서 시간을 구하는 걸 떠올렸는데, 어떤 요소 두개를 max로 비교할 지 모르겠었음. 그래서 그 부분은 답을 보고 구현했다.
위상 정렬을 사용
- …
> [Week03] jiyeon

- BOJ/동전 0/조수지.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> Add: 조수지.py

- Week04/기둥과_보_설치/기둥과_보_설치_조수지.py
- Week04/럭키_스트레이트/럭키_스트레이트_조수지.py
- Week04/문자열_압축/문자열_압축_조수지.py
- Week04/뱀/뱀_조수지.py
- Week04/외벽_점검/외벽_점검_조수지.py
- Week04/자물쇠와_열쇠/자물쇠와_열쇠_조수지.py
- Week04/치킨_배달/치킨_배달_조수지.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> 29 week04 suji

- Week05/과제는_끝나지_않아/김지연.py
- Week05/연구소/김지연.py
- Week05/최소직사각형/김지연.py
- Week05/특정_거리의_도시_찾기/김지연.py
- Problem: [과제는 끝나지 않아](https://www.acmicpc.net/problem/17952)
- Issue: [#33 ]()
- 시도 횟수: 1
- 풀이 시간:
현재 문제를 풀다가 새로운 과제가 등장하면 새로운 과제 풀고 다시 이전 문제를 풀어야하므로 스택이 필요하다고 생각했다.
현재 문제 풀고 새로운 과제 나오면 현재 문제 스택에 넣고.. 를 반복하는데, 스택에 넣을 때 (과제 점수, 남은 시간)을 튜플로 넣어줘서 남은 시간이 0 이되면 점수를 누적해서 더하는 걸로 생각했다. 남은 시간을 넣을 때 처음에 입력으로 주어진 시간을 그대로 넣지 않고, 주어진 시간-1로 해서 넣어줘야 한다는 걸 간과해서 조금 해매었던 기억이 있다. 
1. 과제 입력이 주어지면 score, t 변수에 (과제 점수, 남은 시간-1)를 초기화 해준다. (남은 시간 -1은 과제를 받자마자 시작한 걸로 치면 남은 시간에서 1을 빼줘야한다)
2. `남은시간 == 0` 이되면 누적합을 계속 더해준다.
3. 만약 입력에 새로운 과제가 등장하면 현재 진행하고 있던 과제는 스택에 넣고, 새로운 과제를 score, t에 초기화 한다
위 과정을 반복해준다.
- `O(N)`
---------
- Problem: [최소직사각형](https://school.programmers.co.kr/learn/courses/30/lessons/86491)
- Issue: [#33 ]()
- 시도 횟수: 1
- 풀이 시간:
명함의 가로, 세로 길이가 주어질 때 명함의 가로와 세로 중 큰 수와 작은 수를 구분해서 저장하는 리스트를 만들어서 각 …
> [Week05] jiyeon

- Week05/과제는_끝나지_않아/과제는_끝나지_않아_조수지.py
- Week05/연구소/연구소_조수지.py
- Week05/최소직사각형/최소직사각형_조수지.py
- Week05/특정_거리의_도시_찾기/특정_거리의_도시_찾기_조수지.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> 34 week05 suji

- Week06/국영수/김지연.py
- Week06/숫자_문자열과_영단어/김지연.py
- Week06/연속된_부분_수열의_합/김지연.py
- Week06/이웃한_칸/김지연.py
- Week06/카드_정렬하기/김지연.py
- Problem: [연속된 부분 수열의 합](https://school.programmers.co.kr/learn/courses/30/lessons/178870)
- Issue: [#48 ]()
- 시도 횟수:
- 풀이 시간:
https://mystudylog.tistory.com/95
1. start, end 포인터를 sequence의 인덱스 0을 가리키게 한다.
2. end를 1씩 늘리면서 sequence[start] ~ sequence[end]까지의 누적합을 구하다가 누적합이 k보다 커지면 start에 1을 더하고 다시 누적합을 구한다
3. k와 누적합이 같아지는 순간의 interval을 구해주고 기존 interval과 비교해서 더 짧은 것을 저장해준다 (길이가 짧은 수열 구하기), 이때 start와 end 인덱스를 저장해준다.
- `O(N)`
- Problem: [카드정렬하기](https://www.acmicpc.net/problem/1715)
- Issue: [#48 ]()
- 시도 횟수:
- 풀이 시간:
최소 연산 횟수를 구해야하므로 카드 묶음이 제일 적은 두 개를 더해줘야한다.   
그래서 카드 묶음을 리스트에 넣어주고, 거기서 sort() 내장 함수를 사용해서 정렬 후, 앞의 2개 꺼내서 더해주고, 더해준 결과 리스트에 넣어서 다시 sort()해주고 넣어주고,,, 하면 카드를 꺼내고 다시 넣을 때마다 계속 sort()를 사용하게 된다.   
그럼 대략 O(N^2logN) (sort() 가 O(NlogN), 카드를 꺼내는 반복문 O(N)) 이 돼서 시간초과가 되는 것 같다, O(N^2)만해도 …
> 44 week06 jiyeon

- Week04/기둥과_보_설치/기둥과_보.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> [Week04] yongsun

- Week07/AB/ab_조수지.py
- Week07/가사_검색/가사_검색_조수지.py
- Week07/공유기_설치/공유기_설치_조수지.py
- Week07/단어수학/단어수학_조수지.py
- Week07/수_묶기/수_묶기_조수지.py
- Week07/잃어버린 괄호/잃어버린_괄호_조수지.py
- Week07/주식/주식_조수지.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> [Week07] suji

- BOJ/스택 수열/김지연.py
- Problem: [스택 수열](https://www.acmicpc.net/problem/1874)
- Issue: [#62 ]()
- 시도 횟수:
- 풀이 시간:
스택에 수를 '오름차순'으로 넣는 다는 조건이 있어서 쉽게 해결 가능했다. 스택에 넣을 전역 변수 num을 선언해줘서  스택에 한번 push할 때마다 `num += 1`을 수행해서 다음 push 연산에서 증가된 num을 넣어주도록 했다.
리스트를 활용한 스택 구현
- `O(N)`
시간 복잡도에 대한 chat gpt의 답변...   
시간 복잡도 분석
코드에서 주요 연산이 이루어지는 부분은 for 루프와 while 루프입니다.
for i in range(len(arr)): 루프는 n번 반복되며, 내부의 while 루프 역시 최악의 경우 n번 실행될 수 있습니다.
내부의 while 루프는 조건에 따라 스택에 숫자를 추가하거나, 스택에서 숫자를 제거합니다. 이 과정은 각 숫자마다 한 번씩만 발생하므로, 내부의 while 루프가 중첩으로 여러 번 실행되지 않습니다.
stack.append()와 stack.pop()은 모두 O(1)의 시간 복잡도를 가지는 연산입니다.
> Add: 스택수열.py

- Week08/금광/금광_조수지.py
- Week08/부분합/부분합_조수지.py
- Week08/소수의_연속합/소수의_연속합_조수지.py
- Week08/수_고르기/수_고르기_조수지.py
- Week08/숫자_카드_나누기/조수지.py
- Week08/정수_삼각형/정수_삼각형_조수지.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> [Week08] suji

- Week08/금광/김지연.py
- Week08/부분합/김지연.py
- Week08/소수의_연속합/김지연.py
- Week08/수_고르기/김지연.py
- Week08/정수_삼각형/김지연.py
- Problem: [소수의 연속합](https://www.acmicpc.net/problem/1644)
- Issue: [#53 ]()
- 시도 횟수:
- 풀이 시간:
주어진 수에서 소수를 구한후 투포인터를 활용해서 구현하는 것까지는 수월했는데 소수를 구하는 부분에서 자꾸 시간초과가 났다.
```python
for i in range(2, n+1):
check = True
for j in range(2, i):
if i % j == 0:
check = False
break
if check == True:
num.append(i)
```
주어진 n에 대해서 완전탐색으로 소수를 판별했는데 n 최대 4,000,000이므로 이중 for문으로 소수를 판별하면 시간초과가 나는 것 같다...
백준 질문 게시판을 보니 소수를 찾는 과정에서 길이가 n인 리스트를 선언해서 초반에 탐색된 소수를 기준으로 2,3,4,.. 배수인 수는 리스트에서 False로 처리해 주는 식으로 소수가 아닌 것을 하나씩 제거해 나가는 방법으로 탐색했다.
```python
primes = [False, False] + [True] * (n-1)
data = []
for i in range(2, n+1):
if primes[i]:
data.append(i)
j = 2
while i*j <= n:
primes[i*j] = False
j += 1
```
찾아보니까 소수를 구하는 알고리즘 `에라토스테네스의 체`라는게 있더라... 
관련 글: https://mystudylog.tistory.com/106
소수를 효율적으로 찾아서 투 포인터를 이용하여 구간 …
> [Week08] jiyeon

- Week09/경로 찾기/경로_찾기_조수지.py
- Week09/다리를 지나는 트럭/다리를_지나는_트럭_조수지.py
- Week09/병사 배치하기/병사_배치하기_조수지.py
- Week09/퇴사/퇴사_조수지.py
- Week09/플로이드/플로이드_조수지.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> [Week09] suji

- Week10/최단경로/최단경로_조수지.py
- Week10/카드2/카드2_조수지.py
- Week10/호텔 대실/호텔_대실_조수지.py
- Week10/회의실 배정/회의실_배정_조수지.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> [Week10] suji

- Week10/최단경로/김지연.py
- Week10/카드2/김지연.py
- Week10/호텔 대실/김지연.py
- Week10/회의실 배정/김지연.py
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> [Week10] jiyeon

- Week09/경로 찾기/hun.java
- Week09/다리를 지나는 트럭/hun.java
- Week09/병사 배치하기/hun.java
- Week09/전력망을 둘로 나누기/hun.java
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> Week09 조성훈

- Week10/최단경로/hun.java
- Week10/카드2/hun.java
- Week10/호텔 대실/hun.java
- Week10/회의실 배정/hun.java
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> Weak10 조성훈

- Week08/금광/hun.java
- Week08/부분합/hun.java
- Week08/소수의_연속합/hun.java
- Week08/수_고르기/hun.java
- Week08/정수_삼각형/hun.java
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
> Week08 조성훈
